language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

cache:
  directories:
    - node_modules

before_script:
  - npm install seneca$SENECA_VER

after_script:
  npm run coverage
